name: deploy

on:
  repository_dispatch:
    types:
      - bridge_deploy

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install -g yarn
      - run: yarn
      - run: yarn format
      - run: PATH_PREFIX=${{github.event.repository.name}} yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.BRIDGESECRET }}
          publish_dir: ./public
